name: Production Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        uses: ./.github/actions/build-image

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Reject prior pending deployments
        run: |
          ENVIRONMENT="production"
          REPO=$(echo $GITHUB_REPOSITORY)
          PENDING_DEPLOYMENTS=$(gh api -X GET "/repos/$REPO/deployments?environment=$ENVIRONMENT" \
            | jq -r '.[] | select(.state == "pending") | .id')

          for DEPLOYMENT_ID in $PENDING_DEPLOYMENTS; do
            gh api -X POST "/repos/$REPO/deployments/$DEPLOYMENT_ID/statuses" \
              -F state=rejected
          done

      - name: Deploy
        uses: ./.github/actions/deploy
