name: Production Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        uses: ./.github/actions/build-image

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/deploy
