name: Staging Deploy

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize

jobs:
  deploy-main-to-staging:
    runs-on: ubuntu-latest
    environment: staging
    concurrency: deploy-to-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bail if a PR already exists labeled 'deploying to staging'
        run: echo "Bailing if a PR already exists labeled 'deploying to staging'"

  deploy-branch-to-staging:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'deploying to staging') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'deploying to staging'))
    runs-on: ubuntu-latest
    environment: staging
    concurrency: deploy-to-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for Existing PRs labeled 'deploying to staging'
        run: echo "Checking for existing PRs labeled 'deploying to staging'"
      - name: Build Image
        uses: ./.github/actions/build-image
      - name: Deploy
        uses: ./.github/actions/deploy

  reset-staging:
    if: github.event.action == 'unlabeled' && github.event.label.name == 'deploying to staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Reset Staging
        run: echo "Resetting staging by re-running the latest `main` staging deployment"
