name: Production Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if Docker Image Is Built
        run: echo "Checking if Docker Image Is Built..." # If docker image is already built, we don't need to build it again (e.g., in the case of a rollback)
      - name: Build and Push Image
        run: echo "Building and pushing image"

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build-image
    steps:
      - name: Deploy
        run: echo "Deploying"
