name: Staging Deploy

on:
  issue_comment:
    types:
      - created

jobs:
  deploy-to-staging:
    if: >-
      github.event.issue.pull_request &&
      format(github.event.comment.body) == 'deploy to staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        uses: ./.github/actions/build-image
      - name: Deploy
        uses: ./.github/actions/deploy
